name: Scrape
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  scrape:
    name: "Scrape latest photo"
    runs-on: ubuntu-latest
    steps:
      - name: "(setup) checkout"
        uses: actions/checkout@v3

      - name: "(setup) deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: deno run
        run: deno run --unstable --allow-net --allow-read --allow-write main.ts

      - name: commit + push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "adamstirtan@gmail.com"
          git config --local user.name "Adam Stirtan"
          git add .
          git commit -m "[$(date +"%F %H:%M:%S %Z")]: new photo captured"
          git push
